### ISSUE TITLE
Implement example micro service in Kotlin

### ISSUE THREAD

**Issue by lreimer** [lreimer/everything-as-code#1]
Use KumuluzEE or maybe Payara micro edition.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/lreimer/everything-as-code/1/1c0da3d7-b08c-4319-b2b4-8845b692eefe/227bf29f-cc84-4f43-acb7-773e160b2736) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
