### ISSUE TITLE
Add Dockerfile to package micro service

### ISSUE THREAD

**Issue by lreimer** [lreimer/everything-as-code#10]
Use the K8S or Fabric8.io Docker base image.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/lreimer/everything-as-code/10/1c0da3d7-b08c-4319-b2b4-8845b692eefe/41aca395-5a59-41cf-b8d6-cf4abfb73a90) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
