### ISSUE TITLE
Write basic unit and integration tests with Groovy

### ISSUE THREAD

**Issue by lreimer** [lreimer/everything-as-code#2]
Ue Spock as testing framework.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/lreimer/everything-as-code/2/1c0da3d7-b08c-4319-b2b4-8845b692eefe/6dc2cd5d-c097-4020-a99b-58bed7c43b3f) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
