### ISSUE TITLE
Use latest Jenkins DSL to define jobs

### ISSUE THREAD

**Issue by lreimer** [lreimer/everything-as-code#4]
Implement Pipeline as code using latest Jenkins version.
Run Jenkins as Docker image or something on GCE.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/lreimer/everything-as-code/4/1c0da3d7-b08c-4319-b2b4-8845b692eefe/264fa49c-1269-409a-b35a-dd139861f944) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
