### ISSUE TITLE
Define SEU with required software packages

### ISSUE THREAD

**Issue by lreimer** [lreimer/everything-as-code#6]
Use SEU-as-code to define a multi platform SEU.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/lreimer/everything-as-code/6/1c0da3d7-b08c-4319-b2b4-8845b692eefe/3e5fbe1a-de2b-4f7a-92d7-b8fc24bfdc05) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by lreimer** [comment]
We need the following dependencies:
- Gradle
- Maven (optional)
- Scala
- Kotlin
- Groovy
- Ruby (optional)
